name: balenaCloud 

on:
 pull_request:
    types: [opened, synchronize, closed]
    branches:
      - master

jobs:
  deploy-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: balena-io/deploy-to-balena-action@master
        name: Deploy to balenaCloud
        with:
          balena_token: ${{ secrets.BALENA_TOKEN }}
          fleet: balenalabs/balenasound
          versionbot: true
      - name: Log release ID built
        run: echo "Built release ID ${{ steps.build.outputs.release_id }}"